#!/usr/bin/env python3
"""Generates src/device/XqGlyphs.h: 20x20 1-bit bitmaps of the traditional
Xiangqi piece characters, rendered from a CJK TrueType font.

Run manually when changing glyphs (the header is committed):
    python3 companion/tools/gen_glyphs.py [path/to/cjk-font.ttf]

On macOS the system PingFang/Hiragino fonts work; on Linux pass e.g. a Noto
Sans CJK path. Requires Pillow.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SIZE = 20
# (identifier, red char, black char) per piece code order GEN..SOL.
PIECES = [
    ("GEN", "帥", "將"),  # 帥 / 將
    ("ADV", "仕", "士"),  # 仕 / 士
    ("ELE", "相", "象"),  # 相 / 象
    ("HOR", "傌", "馬"),  # 傌 / 馬
    ("CHA", "俥", "車"),  # 俥 / 車
    ("CAN", "炮", "砲"),  # 炮 / 砲
    ("SOL", "兵", "卒"),  # 兵 / 卒
]

CANDIDATE_FONTS = [
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/STHeiti Light.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
]


def load_font() -> ImageFont.FreeTypeFont:
    paths = [sys.argv[1]] if len(sys.argv) > 1 else CANDIDATE_FONTS
    for path in paths:
        try:
            return ImageFont.truetype(path, SIZE - 2)
        except OSError:
            continue
    raise SystemExit("no CJK font found; pass a TTF/TTC path")


def render(ch: str, font) -> list[int]:
    img = Image.new("1", (SIZE, SIZE), 0)
    draw = ImageDraw.Draw(img)
    box = draw.textbbox((0, 0), ch, font=font)
    w, h = box[2] - box[0], box[3] - box[1]
    draw.text(((SIZE - w) // 2 - box[0], (SIZE - h) // 2 - box[1]), ch, font=font, fill=1)
    rows = []
    for y in range(SIZE):
        bits = 0
        for x in range(SIZE):
            if img.getpixel((x, y)):
                bits |= 1 << (SIZE - 1 - x)
        rows.append(bits)
    return rows


def main() -> None:
    font = load_font()
    out = [
        "// GENERATED by companion/tools/gen_glyphs.py; do not edit by hand.",
        "// 20x20 1-bit glyphs of the traditional Xiangqi piece characters.",
        "// Each row is the top 20 bits of a uint32_t, MSB = leftmost pixel.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace chessink {",
        "",
        f"constexpr int kXqGlyphSize = {SIZE};",
        "",
    ]
    for ident, red, black in PIECES:
        for colour, ch in (("RED", red), ("BLACK", black)):
            rows = render(ch, font)
            out.append(f"// U+{ord(ch):04X}")
            out.append(f"constexpr uint32_t kXq{ident}_{colour}[{SIZE}] = {{")
            for i in range(0, SIZE, 5):
                chunk = ", ".join(f"0x{v:05X}u" for v in rows[i : i + 5])
                out.append(f"    {chunk},")
            out.append("};")
            out.append("")
    out += [
        "// Lookup: [piece 1..7][red=0/black=1] -> glyph rows.",
        "constexpr const uint32_t* kXqGlyphs[8][2] = {",
        "    {nullptr, nullptr},",
    ]
    for ident, _, _ in PIECES:
        out.append(f"    {{kXq{ident}_RED, kXq{ident}_BLACK}},")
    out += ["};", "", "}  // namespace chessink", ""]
    Path("src/device/XqGlyphs.h").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote src/device/XqGlyphs.h ({len(PIECES) * 2} glyphs)")


if __name__ == "__main__":
    main()
